from .unit import Unit
from .basica import Basica
from .branch import Branch
from .date import Date
from .egresado import Egresado
from .level import Level
from .modality import Modality
from .privilege import Privilege
from .program import Program
from .programModality import ProgramModality
from .role import Role
from .rolePrivilege import RolePrivilege
from .sex import Sex
from .titulado import Titulado
from .unitProgram import UnitProgram
from .CatEstatus import CatEstatus
from .CatRama import CatRama
from .CatRoles import CatRoles
from .CatUnidadAcademica import CatUnidadAcademica
from .Usuario import Usuario